In [1]:
import numpy as np

# making a numpy array

In [2]:
myarr = np.array([1,5,8,9])

In [3]:
myarr|

SyntaxError: invalid syntax (281775661.py, line 1)

In [4]:
myarr

array([1, 5, 8, 9])

**give it a datatype!**


In [5]:
myarr = np.array ([1,5,8,9], np.int64)

In [6]:
myarr

array([1, 5, 8, 9], dtype=int64)

here, int64 means it is 64 bit integer.
you can use int8, int32, int128, etc.

but keep your number within the range of specified datatype... like if we say

In [7]:
baburao = np.arr([1,346363,23,13, 5,2], np.int8)

AttributeError: module 'numpy' has no attribute 'arr'

In [8]:
baburao = np.array([1,346363,23,13, 5,2], np.int8)

for array creation, use np.array([])  !!!!!!!!!!

In [9]:
baburao

array([ 1, -5, 23, 13,  5,  2], dtype=int8)

here, 346363 is too large for 8 bit integer so it returns a negative number

# array indexing

In [10]:
myarr[3]

9

In [11]:
myarr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

shows error because it is 1d array and not 2d

In [12]:
myarr = np.array([1,5,8,9], [2,86,34,134], np.int128)

AttributeError: module 'numpy' has no attribute 'int128'

In [13]:
myarr = np.array([1,5,8,9], [2,86,34,134], np.int64)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

you had created 2d array wrongly! the correct method is:

In [15]:
myarr = np.array([[1,5,8,9], [2,86,34,134]], np.int64)

In [16]:
myarr[1][3]

134

returns element from 2nd row (index 1) and 4th column (index 3)

In [18]:
myarr = np.array([[1,5,8,9], [2,86,34,134]], np.int128)

AttributeError: module 'numpy' has no attribute 'int128'

**note: JUPYTER NOTEBOOK ONLY SUPPORTS INTEGER DATATYPE BITS TILL 64, i.e. int64 and not beyond that.................. you can only use int8, int16, int32 and int64**

*changing elements within array*

In [19]:
myarr[0,3]=32

In [20]:
myarr

array([[  1,   5,   8,  32],
       [  2,  86,  34, 134]], dtype=int64)

In [21]:
myarr.dtype

dtype('int64')

returns datatype of array

In [22]:
myarr.shape

(2, 4)

Returns number of rows and number of columns in array

In [23]:
myarr.size

8

returns total length of array or total no. of elements in array