In [1]:
import numpy as np

In [2]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [3]:
arr= np.array(x)

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.sum(axis=0)

array([12, 15, 18])

# here, arr.sum(axis=0) calculates sum of all elements along the 0th axis

**0th axis is pointing columns vertically downwards, so sum of elements along axis 0 will be:
first: 1+4+7 = 12
second: 2+5+6 = 15
third: 3+6+9 = 18**

In [6]:
arr.sum(axis=1)

array([ 6, 15, 24])

# here, arr.sum(axis=1) calculates sum of all elements along the 1th axis

**1th axis is pointing rows horizontally from left to right, so sum of elements along axis 1 will be:
first: 1+2+3 = 6
second: 4+5+6 = 15
third: 7+8+9 = 24**