In [1]:
import numpy as np

In [2]:
x = np.arange(9)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x = np.resize((3,3))

TypeError: _resize_dispatcher() missing 1 required positional argument: 'new_shape'

In [5]:
x = np.reshape((3,3))

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [6]:
x = x.reshape((3,3))

In [7]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Array Transpose = .T**

In [8]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

it transposes the given array - rows to columns and columns to rows 

In [9]:
x = x.T

In [10]:
x

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

**flat**


In [11]:
x.flat

In [13]:
for item in x.flat:
    print(item)

0
3
6
1
4
7
2
5
8


arr.flat makes the given array to be able to iterate over by using a for loop

**ndim**

In [14]:
x.ndim

2

returns number of dimensions of the array

**nbytes**

In [15]:
x.nbytes

36

returns total bytes consumed by elements of array

**max and min element**

**argmax()**

In [16]:
a = np.array([1,3,47,909,134,1,4])

In [17]:
a.argmax()

3

returns the index of max element in array

**argmin()**

In [18]:
a.argmin()

0

returns the index min element in array (returns lowest possible index if element occurs more than once)

**argsort()**

In [19]:
a.argsort()

array([0, 5, 1, 6, 2, 4, 3], dtype=int64)

it returns the indices of array after sorting - means what order of indices will make the given array sorted

# arg functions for 2d array

In [26]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
x.argmax()

8

In [21]:
x.argmin()

0

In [22]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

**here normal x.argsort() on 2d array gives the relative sorting order within a row**

In [27]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [28]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

**argsort along the axis gives relative positions of sorted elements**

In [30]:
p = np.array([[7,2,1], [2,4,0], [9,3,10]])

In [31]:
p

array([[ 7,  2,  1],
       [ 2,  4,  0],
       [ 9,  3, 10]])

In [32]:
p.argsort(axis=0)

array([[1, 0, 1],
       [0, 2, 0],
       [2, 1, 2]], dtype=int64)

In [33]:
p.argsort(axis=1)

array([[2, 1, 0],
       [2, 0, 1],
       [1, 0, 2]], dtype=int64)

In [34]:
p.reshape((9,1))

array([[ 7],
       [ 2],
       [ 1],
       [ 2],
       [ 4],
       [ 0],
       [ 9],
       [ 3],
       [10]])