In [1]:
import numpy as np

# 1. Conversion from other Python structures (lists, tuples, etc.)

In [2]:
bhau = np.array([[1,2,3], [4,5,6], [7,8,9])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (500873147.py, line 1)

In [3]:
bhau = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [4]:
bhau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
bhau.dtype

dtype('int32')

In [6]:
bhau.shape

(3, 3)

In [7]:
bhau.size

9

this was a list

**dictionary**


In [8]:
chintu = np.array({21,2541,23,475})

In [9]:
chintu

array({21, 475, 2541, 23}, dtype=object)

here it shows datatype as object............

it is advised to use list arrays of int or floating point numbers rather than objects when huge calculations are involved>>

# 2. Intrinsic numpy array creation objects (in-built fucntions like arange, zeros, ones,etc.)

**zeros**


In [10]:
ZeroArr = np.zeros((3,5))

In [11]:
ZeroArr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

creates an array of 3 rows and 5 columns filled with zeroes

In [12]:
ZeroArr.dtype

dtype('float64')

In [13]:
ZeroArr.shape

(3, 5)

In [14]:
ZeroArr.size

15

**arange**


In [17]:
RangeArr = np.array(arange(10))

NameError: name 'arange' is not defined

In [18]:
RangeArr = np.arange(10)

In [19]:
RangeArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arange returns an array starting from 0 to n-1

**linspace**

In [20]:
LinspaceArr = np.linspace(1,4,10)

In [21]:
LinspaceArr

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

linspace(a,b,m) returns equally linearly spaced m numbers from range a to b 

In [22]:
babuarr = np.linspace(1,1000,6)

In [23]:
babuarr

array([   1. ,  200.8,  400.6,  600.4,  800.2, 1000. ])

In [24]:
babuarr.dtype

dtype('float64')

In [25]:
babuarr.shape

(6,)

In [26]:
babuarr.size

6

**empty**

In [27]:
EmptyArr = np.empty(3,5)

TypeError: Cannot interpret '5' as a data type

In [28]:
EmptyArr = np.empty((3,5))

In [29]:
EmptyArr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
EmptyArr = np.empty((4,9))

In [31]:
EmptyArr 

array([[1.08142701e-311, 1.08142456e-311, 1.37961641e-306,
        8.34424342e-308, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [8.01095173e-307, 2.22522597e-306, 9.34611148e-307,
        1.60220393e-306, 1.42417221e-306, 1.95820216e-306,
        1.42417629e-306, 1.95820216e-306, 1.86919513e-306],
       [9.34604358e-307, 8.90111708e-307, 6.89806849e-307,
        8.45602762e-307, 9.34608432e-307, 6.89813978e-307,
        1.24610723e-306, 1.60219035e-306, 8.90111708e-307],
       [6.89806849e-307, 8.45602762e-307, 9.34608432e-307,
        6.89813978e-307, 1.02360392e-306, 1.42410974e-306,
        1.73157382e-260, 1.47816155e-309, 2.56898228e-312]])

np.empty((m,n)) gives an empty array of m x n  elements filled with random elements.......... you can assign any value to it

**empty_like**

In [32]:
ArrEmpty_Like = np.empty_like(LinspaceArr)

In [33]:
ArrEmpty_Like

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

if you had made an old array then np.empty_like copies its size and elements which can be initialized later with any other ones..... this is done for space efficiency

**identity**

In [34]:
Identity_Matrix = np.identity(50)

In [35]:
Identity_Matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
Identity_Matrix.shape

(50, 50)

np.identity(n) creates an identity matrix of n x n elements (Identity matrix is somthing in which only diagonal elements are ones and rest are zeroes) 

**reshape**

In [37]:
bahin = np.arange(100)

In [38]:
bahin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
bahin.reshape((4, 25))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
bahin.reshape((2,50))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [41]:
bahin.reshape((5,20))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [42]:
bahin.reshape((7,14))

ValueError: cannot reshape array of size 100 into shape (7,14)

arr.reshape((m,n)) resizes the given arr array into m rows and n columns...........remember that m x n should be equal to the number of elements in array...

In [43]:
bahin = bahin.reshape((4,25))

In [44]:
bahin

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
bahin.shape

(4, 25)

**ravel**

In [46]:
bahin.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

arr.ravel() makes it turn into its own from - if its 1d array intially then it converts it into 1d array

In [47]:
bahin = bahin.ravel()

In [48]:
bahin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
bahin.shape

(100,)